### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by spmedia** [faizann24/wifi-bruteforcer-fsecurify#1]
Hello,

When I hit 'Scan Networks', no networks ever show up, just a blank black page.

Any ideas?

Android 6.0.1
Galaxy S7 edge

Thanks!

**Comment by zjq777007** [comment]
me,too!my device is nexus6p 6.0.1

**Comment by pieterhouwen** [comment]
Same for me, I have a Huawei P8 Lite with Android 6.0

**Comment by mchllngr** [comment]
Scanning for networks needs permission "ACCESS_COARSE_LOCATION" since Android 6.0. This does not seem to be implemented yet.

**Comment by faizann24** [comment]
Can anyone change the code and make a pull request. I am a little busy and don't want to make you people wait. 

Best Regards.

**Comment by spmedia** [comment]
@mchllngr wanna work your wizardry and fix/implement ACCESS_COARSE_LOCATION ? <3

**Comment by mchllngr** [comment]
@spmedia no, I'm sorry. The repository is missing its gradle files which are needed for building. I don't know why. Maybe the app is created with an other IDE (than Android Studio) which doesn't use gradle.

**Comment by spmedia** [comment]
Thanks for the reply.

@faizann24 seems you have some work to do before this is usable...

**Comment by faizann24** [comment]
I have added the complete project in a rar file in the source code. And the project was done on Android Studio.

Best Regards.

**Comment by huclengyue** [comment]
I repair this issue, And has been pushed

**Comment by AdityaAnand1** [comment]
@faizann24 Thanks for adding the full Android Studio project, but why not have the whole project under "sourcecode" directory in the first place? It kind of undermines the whole point of git :)

**Comment by spmedia** [comment]
@huclengyue thank you. I uninstalled and reinstalled your version. Wifi SSIDs showing now and cracking appears to be 'working'. Will test more later today.
