### ISSUE TITLE
Upload to F-droid

### ISSUE THREAD

**Issue by RootLUG** [faizann24/wifi-bruteforcer-fsecurify#3]
It might be nice to have it uploaded into the f-droid.org repository under security category. This way users can get also updates when a new version is released

**Comment by faizann24** [comment]
Sure, I will.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/faizann24/wifi-bruteforcer-fsecurify/issues/3#issuecomment-271559510

@faizann24, I don't see it on there, at https://search.f-droid.org/?q=FSecurity&lang=en. What's the URI of the package request?
